# Generated by Django 5.1.3 on 2024-11-29 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_contributionplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.societymember'),
        ),
    ]
