# Generated by Django 5.1.3 on 2024-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_expense_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societymember',
            name='email',
        ),
        migrations.AddField(
            model_name='societymember',
            name='shares',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
